---
:environment:
  :test:
    dbname: adventure-test
    user:  root
    pass:  ***
  :development:
    dbname: adventures
    user: root
    pass:  ***
  :production:
    dbname: adventure-production
    user: root
    pass: ***
:admin:
  :host: 10.247.8.109   #  localhost or ip
  :port: 2480
  :user: root
  :pass: ***
:logger: stdout           # 'file' or 'stdout'
:namespace: Arcade        # Default Namespace
:autoload: true           # load model if a link is detected in a record

